name: Test Schema

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"
      - "*.md"
  workflow_dispatch:
  pull_request:
    paths:
      - "**/pixi.toml"
      - "schema/**"
      - "**/schema.yml"

permissions: read-all

jobs:
  test-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: prefix-dev/setup-pixi@main
        with:
          cache: true
          environments: schema
      - name: Ensure schema is up-to-date
        run: |
          pixi run -e schema generate-schema
          git diff --exit-code
      - name: Test Schema
        run: |
          pixi run -e schema test-schema
          git diff --exit-code
