name: "Test common wheel files for installation with pixi"

on:
  workflow_call:
    inputs:
      sha:
        type: string
        description: "The commit sha"
        required: true
      arch:
        type: string
        description: "The architecture of the file to test"
        required: true
      runs-on:
        type: string
        description: "The operating system to run the tests on"
        required: true

jobs:
  test_common_wheels:
    name: Test Installation of Common Wheels | ${{ inputs.arch }}
    runs-on: ${{ inputs.runs-on }}
    env:
      TARGET_RELEASE: "${{ github.workspace }}/target/pixi/release"
      LOGS_DIR: "${{ github.workspace }}/tests/wheel_tests/.logs"
      SUMMARY_FILE: "${{ github.workspace }}/tests/wheel_tests/.summary.md"
      PYTHONIOENCODING: utf-8
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download binary from build
        uses: actions/download-artifact@v4
        with:
          name: pixi-${{ inputs.arch }}-${{ inputs.sha }}
          path: ${{ env.TARGET_RELEASE }}
      - name: Test common wheels
        run: ${{ env.TARGET_RELEASE }}/pixi run test-common-wheels-ci --pixi-exec ${{ env.TARGET_RELEASE }}
      - name: Write .summary.md to Github Summary
#        if: ${{ !contains(inputs.arch, 'windows') && always() }}
        shell: bash
        run: |
          cat ${{ env.SUMMARY_FILE }} >> $GITHUB_STEP_SUMMARY
#      - name: Write .summary.md to GitHub Summary (Windows)
#        if: ${{ contains(inputs.arch, 'windows') && always() }}
#        shell: pwsh
#        run: |
#          $resolvedPath = Resolve-Path $env:SUMMARY_FILE
#          Get-Content $resolvedPath | Out-File -Append -FilePath $env:GITHUB_STEP_SUMMARY
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: wheel-tests-logs-${{ inputs.arch }}
          include-hidden-files: true
          path: ${{ env.LOGS_DIR }}
